### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Madhurireddy1** [ShivamBhirud/Team-up#17]
Hey, I was trying to run your project but got an error. I've searched online but was unable to resolve it. Could you help me with this? thankyou.
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

**Comment by ShivamBhirud** [comment]
This error occurred because the DB setting in the project is set for the production purpose that is for deployment of the web app. However, to run this django project you need to mention the Sqlite3 DB connection in the settings.py file.

The fix:
In Team_Up folder goto settings.py file.
Un-comment line  68-73
Comment or remove line 76-80.

Now, the DB error should be resolved. 

Along with this, also make sure that you comment out Debug settings and secret key and then set Debug = True and add a secret key as any random string in the same settings.py file. In short, whatever you see under Production settings comments should be replaced as I mentioned above. I hope that helps!

**Comment by Madhurireddy1** [comment]
Thankyou .
